---
- name: pull lightingAutomation
  become: true
  become_user: "{{ user }}"
  git:
    repo: https://github.com/SuperLimitBreak/lightingAutomation.git
    dest: "{{ src_folder }}/lightingAutomation"
    update: yes
  register: checkout

- name: install lightinAutomation
  become: true
  become_user: "{{ user }}"
  shell: make clean && make install
  args:
    chdir: "{{ src_folder }}/lightingAutomation"
  when: checkout.changed

