---
- hosts: all
  user: root
  vars:
    src_folder: /super_limit_break/
  roles:
    - base
    - libs
    - pentatonicHero
    - displayTrigger
    - lightingAutomation
    - voteBattle
    - graphical
    - monit
    - lexrus.ansible-role-docker
