---
- name: pull displayTrigger
  remote_user: "{{ user }}"
  git:
    repo: https://github.com/SuperLimitBreak/displayTrigger.git
    dest: "{{ src_folder }}/displayTrigger"
    update: yes
  register: checkout

- name: apt deps
  apt:
    pkg: python3-dbus

- name: install displayTrigger
  remote_user: "{{ user }}"
  shell: make clean && make install
  args:
    chdir: "{{ src_folder }}/displayTrigger"
  when: checkout.changed

