---
- name: remove conflicting apt deps
  apt:
    pkg: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - accountsservice
    - update-notifier

# This file causes issues selecting desktop environment
- name: remove conflict accountservice file
  file:
    path: "/var/lib/AccountsService/users/{{ user }}"
    state: absent

- name: apt deps
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - lightdm
    - libglib2.0-bin
    - xserver-xorg
    - openbox
    - unclutter  # hide cursor when not in use

- name: add google-chrome apt key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: add google-chrome apt repo
  copy:
    content: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    dest: "/etc/apt/sources.list.d/google-chrome.list"
  register: googlerepo

- name: install google chrome
  apt:
    pkg: google-chrome-stable
    update_cache: yes

- name: auto login {{ user }}
  template:
    src: autologin.conf.j2
    dest: "/etc/lightdm/lightdm.conf.d/autologin.conf"
    mode: 0644

- name: set desktop environment
  become: true
  become_user: "{{ user }}"
  copy:
    src: .dmrc
    dest: "/home/{{ user }}/.dmrc"
    mode: 0644
    owner: "{{ user }}"

- name: create openbox config folder
  file:
    path: "/home/{{ user }}/.config/openbox/"
    state: directory
    mode: 0744
    owner: "{{ user }}"

- name: graphical autostart
  copy:
    src: autostart
    dest: "/home/{{ user }}/.config/openbox/autostart"
    mode: 0644
    owner: "{{ user }}"
