---
- name: apt deps
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - openssh-server
    - python
    - python-dev
    - python-virtualenv
    - python3
    - python3-dev
    - python3-setuptools
    - build-essential
    - sudo
    - git
    - apt-transport-https

- name: ensure user in sudo group
  user:
    name: "{{ user }}"
    groups: sudo
    append: yes
    state: present

- name: create {{ user }} sudoers file
  template:
    src: passwdless.j2
    dest: "/etc/sudoers.d/{{ user }}-nopasswd"
    mode: 0640

# Will be putting our packages here
- name: create {{ src_folder }}
  file:
    path: "{{ src_folder }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
