---
- name: create user
  user: name=slb password=password shell=/bin/bash

- name: apt deps
  apt: pkg={{ item }} state=installed
  with_items:
    - openssh-server
    - python
    - python-dev
    - python-virtualenv
    - python3
    - python3-dev
    - python3-setuptools
    - build-essential
    - sudo
    - git

# Will be putting our packages here
- name: create opt
  file:
    path: /opt
    state: directory
    mode: 0777
