---
- name: apt deps
  apt: pkg={{ item }} state=installed
  with_items:
    - openssh-server
    - python
    - python-dev
    - python-virtualenv
    - python3
    - python3-dev
    - python3-setuptools
    - build-essential
    - sudo
    - git

- name: ensure user in sudo group
  user:
    name: "{{ user }}"
    groups: sudo
    append: yes
    state: present

- name: touch {{ user }} sudoers file
  file:
    path: "/etc/sudoers.d/{{ user }}-nopasswd"
    state: touch
    mode: 0640
  register: nopasswdfile

- name: edit {{ user }} sudoers files
  copy:
    content: "{{ user }} ALL=(ALL) NOPASSWD: ALL\n"
    dest: "/etc/sudoers.d/{{ user }}-nopasswd"
  when: nopasswdfile.changed

# Will be putting our packages here
- name: create {{ src_folder }}
  file:
    path: "{{ src_folder }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
